Repository flickit-platform/flickit-assessment, pull requests merged in 2024-12, with the labels that each got.

#502 FAC-795 Implement CreateAdviceItem Service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/CreateAdviceItemRequestDto.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/CreateAdviceItemRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/AdviceItem.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevel.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/CreateAdviceItemUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/CreateAdviceItemPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/adviceitem/CreateAdviceItemUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemServiceTest.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review

#504 FAC-796: Implement LoadItemAdviceItem service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemListRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemListUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/LoadAdviceItemListPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemListUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AdviceItemMother.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaRepository.java
Labels: Ready to Review

#508 FAC-808: Modify AdviceItemServiceAddresses
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/CreateAdviceItemRequestDto.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/CreateAdviceItemRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemListRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/UpdateAdviceItemRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AssessmentResult.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/UpdateAdviceItemUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/LoadAdviceItemPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/adviceitem/UpdateAdviceItemPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessmentresult/LoadAssessmentResultPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/adviceitem/UpdateAdviceItemUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAssessorAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AssessmentResultMother.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review

#509 FAC- 809: Add MANAGE_ADVICE_ITEM Permission
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/CreateAdviceItemServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/UpdateAdviceItemServiceTest.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
Labels: Ready to Review

#511 FAC-802: Implement GetAdviceCostLevel Service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemCostLevelsRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/CostLevel.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemCostLevelsUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemCostLevelsService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/CostLevelTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemCostLevelsServiceTest.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review

#513 FAC-804: Implement GetPriorityLevels service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemPriorityLevelsRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevel.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemPriorityLevelsUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemPriorityLevelsService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevelTest.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review

#512 FAC-803: Implement GetAdviceImpactLevels service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/adviceitem/GetAdviceItemImpactLevelsRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/ImpactLevel.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemImpactLevelsUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemImpactLevelsService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/ImpactLevelTest.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review

#514 FAC-812: consider answer range model in update kit by dsl
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/UpdateKitPersisterContext.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/AnswerRangeUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/SubjectQuestionnaireUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/AnswerRangeUpdateKitValidator.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/DslFieldNames.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/InvalidChangeError.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/QuestionUpdateKitValidator.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/AnswerRangeUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/SubjectQuestionnaireUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/AnswerRangeUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/QuestionUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerRangeMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/AnswerOptionDslModelMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/AnswerRangeDslModelMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/SubjectDslModelMother.java
Labels: In Progress

#517 FAC-811: feat add order param to attribute score details
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/crud/Order.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAttributeScoreDetailResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAttributeScoreDetailRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Sort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCaseTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionScoreMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaEntity.java
Labels: Ready to Review

#521 FAC-800 modify confidence level computation algorithm
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java
Labels: Ready to Review

#523 FAC-776: Minor database refactors
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.40.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#522 FAC-816: add evidence count to get attribute score details service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAttributeScoreDetailRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCaseTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
Labels: Ready to Review

#499 FAC-777: Add Scenario Test for Deleting Space
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/DeleteSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java
Labels: Ready to Review, P3

#528 FAC-819 Remove optionImpact due to adding 'value' to option
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/NumberUtils.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/CreateAttributeScoresFileAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Answer.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerOption.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerOptionImpact.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/report/CreateAttributeScoresFileAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerOptionImpactTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentResultTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/SubjectValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionImpactMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/MaturityScoreMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
Labels: Ready to Review

#526 FAC-818: Remove AnswerOptionImpactt from Kit Module
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/QuestionImpact.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionimpact/GetQuestionImpactsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/CreateAnswerOptionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/UpdateAnswerOptionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionImpactsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/GetQuestionImpactsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionImpactMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/Constants.java
Labels: Ready to Review

#498 FAC-784: Feat - Remove `getOptionImpactValue` from ‍‍‍‍‍`Advice` Module
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/OptionImpactWithQuestionImpactView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/AttributeLevelImpactfulQuestionsView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/ImpactfulQuestionView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerOptionImpact.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/AnswerRangeUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/validate/impl/QuestionUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/Constants.java
Labels: pending

#530 FAC-823 Add 'resolved' field to EvidenceJpaEntity & the table
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.41.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#532 FAC-824 Impl comment resolving service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/ResolveCommentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/ResolveCommentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/ResolveCommentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/ResolveCommentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/ResolveCommentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/ResolveCommentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/EvidenceMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: In Progress

#529 FAC-822: Implemenet ExportKitDsl Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitDslRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/SubjectDslModel.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitDslUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/LoadAnswerRangesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAttributesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDslService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitDslUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDslServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/Constants.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#534 FAC-825_Refine-get-evidences-service-output
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/LoadEvidencesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/ResolveCommentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: Ready to Review

#535 FAC-828: ImplementGetAssessmentDashboard Service
  .gitignore
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentDashboardRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/adviceitem/CountAdviceItemsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountLowConfidenceAnswersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/CountAttributesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/LoadAttributeInsightsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/CountEvidencesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subject/CountSubjectsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectinsight/LoadSubjectInsightsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeInsightMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
Labels: Ready to Review

#539 AC-839: Rename Objects title in GetAssessmentDashboard Service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
Labels: Ready to Review

#531 FAC-829: Extract user locale
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/MessageBundle.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/locale/LocaleConfig.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/locale/LocaleFilter.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/advice/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#540 FAC-826: Delete Option Impact Table and Entity
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/seq/KitDbSequenceGenerators.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.41.xml
Labels: Ready to Review

#524 FAC-778 Impl expert group deletion test scenario
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/CreateExpertGroupScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/DeleteExpertGroupScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/ExpertGroupTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java
Labels: Ready to Review

#542 FAC-845: fix - Add Forgotten keys in users module
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
Labels: Ready to Review

#537 FAC-833 Add 'approved' field to the attribute insight entity
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeInsight.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/LoadAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/UpdateAttributeInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/UpdateAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeInsightMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.42.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#546 FAC-841: Implement InitAssessmentInsight service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/InitAssessmentInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/InitAssessmentInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/InitAssessmentInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.42.xml
Labels: Ready to Review

#550 FAC-850 Fix-NPE-of-createAttributeAiInsightService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/CreateAttributeScoresFileAdapter.java
Labels: Ready to Review

#538 FAC-834 Impl approve attribute insight service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/ApproveAttributeInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeAiInsightResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeAiInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/GetAttributeInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/UpdateAttributeInsightRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/UpdateAttributeInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attributeinsight/ApproveAttributeInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeAiInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attributeinsight/GetAttributeInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attributeinsight/UpdateAttributeInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/ApproveAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/ApproveAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/GetAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/UpdateAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/ApproveAttributeInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeAiInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/GetAttributeInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/UpdateAttributeInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/ApproveAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/GetAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/UpdateAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
Labels: Ready to Review

#549 FAC-843: Add ReportViewer Role to Assessment Roles
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentUserRoleTest.java
Labels: Ready to Review
