Repository flickit-platform/flickit-assessment, pull requests merged in 2024-10, with the labels that each got.

#358 FAC-634: Implement Update Maturity Level Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/UpdateMaturityLevelRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/UpdateMaturityLevelRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/UpdateMaturityLevelPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#367 FAC-635:feature:Impl CreateLevelCompetenceService
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/DataIntegrityViolationExceptionHandler.java
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/CreateLevelCompetenceRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/CreateLevelCompetenceRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/levelcompetence/CreateLevelCompetenceUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/levelcompetence/CreateLevelCompetenceService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/levelcompetence/CreateLevelCompetenceUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/levelcompetence/CreateLevelCompetenceServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#362 FAC-640: Implement Edit Level Competence Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/UpdateLevelCompetenceRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/UpdateLevelCompetenceRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/levelcompetence/UpdateLevelCompetenceUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/levelcomptenece/DeleteLevelCompetencePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/levelcomptenece/UpdateLevelCompetencePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/levelcompetence/UpdateLevelCompetenceService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/levelcompetence/CreateLevelCompetenceUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/levelcompetence/UpdateLevelCompetenceUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/levelcompetence/UpdateLevelCompetenceServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#365 FAC-644: Implement Delete Maturity Level Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/DeleteMaturityLevelRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/DeleteMaturityLevelUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/DeleteMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/DeleteMaturityLevelUseCaseTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/DeleteMaturityLevelServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P1

#313 FAC-572: Implement Notification for Accepting Assessment Invitations
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/NotificationType.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/AcceptAssessmentInvitationNovuRequestConverter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/notification/AcceptAssessmentInvitationNotificationsCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinvite/AcceptAssessmentInvitationsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvite/AcceptAssessmentInvitationsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvite/notification/AcceptAssessmentInvitationNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvite/notification/AcceptAssessmentInvitationNotificationPayload.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/notification/GrantAssessmentUserRoleNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/MessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinvite/AcceptAssessmentInvitationsServiceTest.java
Labels: Ready to Merge

#377 FAC-660:feature:Change level competence pk
  dev/dsl-parser/docker-compose.yml
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
Labels: Ready to Review

#374 FAC-646: Implement Change Maturity Level Orders Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/DataIntegrityViolationExceptionHandler.java
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/UpdateMaturityLevelOrdersRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/UpdateMaturityLevelOrdersRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/MaturityLevelOrder.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelOrdersUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/UpdateMaturityLevelPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelOrdersService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelOrdersUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelOrdersServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#378 FAC-661: Improve advice narration prompt
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/Assessment.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessment/LoadAssessmentPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AssessmentMother.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review, P2

#317 FAC-591: Implement Creating Simple Kit Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/CreateAssessmentKitRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/CreateAssessmentKitResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/CreateAssessmentKitRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateAssessmentKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateKitByDslUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/CreateAssessmentKitPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitActiveVersionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitversion/CreateKitVersionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitversion/UpdateKitVersionStatusPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/CreateKitByDslService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateAssessmentKitUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/CreateKitByDslServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Merge, P1

#386 FAC-669:fix:Fix not access to old private kits
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.33.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitServiceTest.java
Labels: Ready to Review, P3

#384 FAC-666:feature:Add draftVersionId to GetExpertGroupKitListService output
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/KitWithDraftVersionIdView.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetExpertGroupKitListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetExpertGroupKitListService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/AttributeUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectQuestionnaireUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/AttributeUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectQuestionnaireUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectUpdateKitPersisterTest.java
Labels: Ready to Review, P2

#380 FAC-655:feature:Impl GetKitMaturityLevelsService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitdsl/GetKitDetailRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/GetKitMaturityLevelsRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/MaturityLevelCompetenceMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/MaturityLevelCompetence.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/GetKitMaturityLevelsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/GetKitMaturityLevelsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/GetKitMaturityLevelsUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/GetKitMaturityLevelsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/LevelCompetenceMother.java
Labels: Ready to Review, P1

#395 FAC-675:feature:Impl GetLevelCompetencesService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/GetLevelCompetencesResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/levelcompetence/GetLevelCompetencesRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/levelcompetence/GetLevelCompetencesUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/levelcompetence/GetLevelCompetencesService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/levelcompetence/GetLevelCompetencesUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/levelcompetence/GetLevelCompetencesServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P2

#389 FAC-659: Implement Delete Subject Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/DeleteSubjectRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/DeleteSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/DeleteSubjectPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/DeleteSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/DeleteSubjectUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/DeleteSubjectServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitVersionMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Merge

#382 FAC-656: Implement List of Subject Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/GetSubjectListRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Subject.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/GetSubjectListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/GetSubjectListUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/SubjectMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#403 FAC-681: Add kitVersionId to QuestionImpact's Primary Key
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/QuestionImpactEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.34.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionimpact/DeleteQuestionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionimpact/UpdateQuestionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
Labels: Ready to Review, P2

#387 FAC-658 Impl delete attribute service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/DeleteAttributeRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/DeleteAttributeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/DeleteAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/DeleteAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/DeleteAttributeUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/DeleteAttributeServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: In Progress, P3

#373 FAC-651:feature:Impl UpdateAttributesOrderService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeOrdersRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeOrdersRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeOrdersUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/UpdateAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeOrdersService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeOrdersUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeOrdersServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#415 FAC-693: remove ralation of answer option impact and question impact
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/OptionImpactWithQuestionImpactView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailServiceTest.java
Labels: Ready to Review, P1

#359 FAC-538:feature:Impl UpdateKitAttributeService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/UpdateAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/AttributeUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P2

#379 FAC-645 Impl delete question service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/DeleteQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/DeleteQuestionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/DeleteQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/DeleteQuestionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/DeleteQuestionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/DeleteQuestionServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#417 FAC-540 Impl update questionnaire service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/UpdateQuestionnaireRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/UpdateQuestionnaireRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionnaire/UpdateQuestionnaireUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/UpdateQuestionnairePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionnaire/UpdateQuestionnaireUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#414 FAC-687:feature:Add kitVersionId to pk_fak_answer_option_impact
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.34.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/UpdateAnswerOptionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
Labels: Ready to Review

#409 FAC-686:feature:Impl GetAttributesService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJoinSubjectView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/GetAttributesRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AttributeWithSubject.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/GetAttributesUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAttributesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetAttributesService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/GetAttributesUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetAttributesServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#391 FAC-671: Implement Create Question Impact Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/CreateQuestionImpactRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/CreateQuestionImpactResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/CreateQuestionImpactRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionimpact/CreateQuestionImpactUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionimpact/CreateQuestionImpactUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#407 FAC-683: Implement Get Question Impacts
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/GetQuestionImpactsRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionimpact/GetQuestionImpactsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionImpactsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionimpact/GetQuestionImpactsUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/GetQuestionImpactsServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#388 FAC-670 Impl delete questionnaire service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/DeleteQuestionnaireRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionnaire/DeleteQuestionnaireUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/DeleteQuestionnairePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/DeleteQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionnaire/DeleteQuestionnaireUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/DeleteQuestionnaireServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P2

#381 FAC-657 Impl questionnaires list service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireListItemView.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/GetQuestionnairesResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionnaire/GetQuestionnairesRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionnaire/GetQuestionnairesUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/GetQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionnaire/GetQuestionnairesUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/GetQuestionnaireServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#419 FAC-542 Impl question update service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/CreateQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P1

#406 FAC-684 Imp update questionnaire questions order service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.34.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionsOrderRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionsOrderRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionsOrderUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionsOrderService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionsOrderUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/UpdateSubjectOrdersUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionsOrderServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P2

#399 FAC-673 Impl question impact update service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/UpdateQuestionImpactRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/UpdateQuestionImpactRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionimpact/UpdateQuestionImpactUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionimpact/UpdateQuestionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionimpact/UpdateQuestionImpactService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionimpact/UpdateQuestionImpactUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/UpdateQuestionImpactServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#421 FAC-273:feature:Incorporate advisable in advice
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
Labels: Ready to Review, P1

#420 FAC-698: Fix nullPointerException When ActiveKitversion is null in kitStats Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsServiceTest.java
Labels: Ready to Review, P2

#424 FAC-700: Implement Load Kit Version Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitversion/GetKitVersionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitversion/GetKitVersionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/GetKitVersionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitversion/GetKitVersionUseCaseTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/GetKitVersionServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#425 FAC-273:feature:Move advisable condition
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
Labels: Ready to Review

#422 FAC-697:feature:Add unique constraint to fak_question_impact
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.34.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
Labels: Ready to Review

#427 FAC-702: Initialize subject questionnaire table in activateKitVersion service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subjectquestionnaire/SubjectQuestionnaireJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subjectquestionnaire/SubjectQuestionnaireView.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subjectquestionnaire/SubjectQuestionnaireMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subjectquestionnaire/SubjectQuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subjectquestionnaire/LoadSubjectQuestionnairePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java
Labels: Ready to Review

#428 FAC-704:feature:Add kit version validation to ValidateAssessmentResult service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/DeprecatedVersionException.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/api/ErrorCodes.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/DeprecatedVersionExceptionHandler.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/internal/ValidateAssessmentResult.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/internal/ValidateAssessmentResultTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
Labels: Ready to Review, P2

#429 FAC-705: Implement Migrate AssesmentResult kitVersion Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/MigrateAssessmentResultKitVersionRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/MigrateAssessmentResultKitVersionUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/UpdateAssessmentResultPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/MigrateAssessmentResultKitVersionService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/MigrateAssessmentResultKitVersionUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/MigrateAssessmentResultKitVersionServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentKitMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentresult/AssessmentResultJpaRepository.java
Labels: Ready to Review, P2

#430 FAC-699 Use subject id when updating subject's attribute orders
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeOrdersRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeOrdersRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeOrdersUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/UpdateAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeOrdersService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeOrdersUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeOrdersServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#394 AC-676: Implement Delete Question Impact Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/questionimpact/DeleteQuestionImpactRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/questionimpact/DeleteQuestionImpactUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionimpact/DeleteQuestionImpactService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/questionimpact/DeleteQuestionImpactUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/DeleteQuestionImpactServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#432 FAC-708: Feat - Create `AnswerRange` Table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/seq/KitDbSequenceGenerators.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
Labels: Ready to Review, P1

#401 FAC-677: Implement Delete Answer Option Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/DeleteAnswerOptionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/DeleteAnswerOptionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/DeleteAnswerOptionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/DeleteAnswerOptionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answeroption/DeleteAnswerOptionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/DeleteAnswerOptionServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#404 FAC-682 Impl question options list service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/GetQuestionOptionsRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/GetQuestionOptionsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answeroption/GetQuestionOptionsUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P2

#433 FAC-713: Improve Maturity Level Calculation
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentResultTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/SubjectValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectValueMother.java
Labels: Ready to Merge

#436 FAC-711 Add assessment creator name to kit designer notif
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/ExpertGroupAccessPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/notification/CreateAssessmentNotificationCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentkit/LoadKitInfoPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/expertgroupaccess/LoadExpertGroupMembersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationPayload.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupAccessJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupActiveMemberView.java
Labels: Ready to Review, P1
