Repository flickit-platform/flickit-assessment, pull requests merged in 2024-11, with the labels that each got.

#441 FAC-721: fix - Fix getKitStat bug in Case of Subjects Without Atrributes
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
Labels: Ready to Review

#439 FAC-718 Impl get questionnaire's questions service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/GetQuestionnaireQuestionsRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/GetQuestionnaireQuestionsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionnaireQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/GetQuestionnaireQuestionsUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#438 FAC-715:feature:Add value field to AnswerOptionJpaEntity
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/ImprovableImpactfulQuestionView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/AnswerOptionDslModel.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/CreateAnswerOptionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/validate/impl/QuestionUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/Constants.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/AnswerOptionDslModelMother.java
Labels: Ready to Review

#412 FAC-690 Impl delete updatingt kit version service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitversion/DeleteKitVersionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitversion/DeleteKitVersionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitversion/DeleteKitVersionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/DeleteKitVersionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitversion/DeleteKitVersionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/DeleteKitVersionServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#442 FAC-710:feature:Remove questionId from AnswerOption
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerOption.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answerhistory/GetAnswerHistoryListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerOption.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/CreateAnswerOptionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/validate/impl/QuestionUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/GetQuestionImpactsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
Labels: Ready to Review

#445 FAC-723: Add `value` Parameter to GetQuestionOptions api
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerOption.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/GetQuestionOptionsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java
Labels: Ready to Review

#440 FAC-720 Impl update answer range service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/UpdateAnswerRangeRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/UpdateAnswerRangeRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answerrange/UpdateAnswerRangeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/UpdateAnswerRangePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answerrange/UpdateAnswerRangeUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#400 FAC-674 Impl update answer option service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/AnswerOptionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/UpdateAnswerOptionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/UpdateAnswerOptionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/UpdateAnswerOptionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/UpdateAnswerOptionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answeroption/UpdateAnswerOptionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/UpdateAnswerOptionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: In Progress

#448 FAC-733 Add option impacts when creating a question impact
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/CreateAnswerOptionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactServiceTest.java
Labels: Ready to Review, P2

#446 FAC-726: Add `AnswerRangeId` As anNullable Parameter to Update question api
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/dsl/QuestionDslModel.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P1

#447 FAC-729 Update lastMajorModificationTime
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java
Labels: Ready to Review

#402 FAC-672:feature:Impl CreateAnswerOptionService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.35.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/CreateAnswerOptionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/CreateAnswerOptionResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answeroption/CreateAnswerOptionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AnswerRange.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answeroption/CreateAnswerOptionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/LoadAnswerRangePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/LoadAnswerRangesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/CreateAnswerOptionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answeroption/CreateAnswerOptionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/CreateAnswerOptionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/validate/impl/QuestionUpdateKitValidatorTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/GetKitQuestionnaireDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerRangeMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P3

#456 FAC-739: Test - Add `value` to `AnswerOptionListItem`
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answerrange/GetAnswerRangeListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsServiceTest.java
Labels: Ready to Review

#459 FAC-730:feature:Fix calculate service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectvalue/SubjectValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectvalue/SubjectValueWithSubjectView.java
Labels: Ready to Review

#462 FAC-741:feature:Impl CreateReusableAnswerOption service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/CreateAnswerRangeOptionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/CreateAnswerRangeOptionResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/answerrange/CreateAnswerRangeOptionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answerrange/CreateAnswerRangeOptionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/CreateAnswerRangeOptionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/answerrange/CreateAnswerRangeOptionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/CreateAnswerOptionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/CreateAnswerRangeOptionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerRangeMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review, P2

#413 FAC-48_feature_Integration test
  .github/workflows/ci-cd.yml
  flickit-assessment-core/src/test/resources/application-test.properties
  flickit-assessment-server/pom.xml
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/data/config/MinioTestContainerHolder.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/data/config/PostgresTestContainerHolder.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/auth/JwtTokenTestUtils.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/AddSpaceMemberRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateExpertGroupRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateSpaceRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateUserRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/MultiPartFileMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/helper/persistence/DatabaseTruncator.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/helper/persistence/JpaTestTemplate.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/AbstractScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/ScenarioContext.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/CreateExpertGroupScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/ExpertGroupTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/spaceuseraccess/AddSpaceMemberScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/spaceuseraccess/SpaceUserAccessTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/user/CreateUserScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/user/UserTestHelper.java
  flickit-assessment-server/src/test/resources/application-test.properties
  flickit-assessment-server/src/test/resources/logback-test.xml
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/CreateExpertGroupRequestDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/CreateSpaceRequestDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/spaceuseraccess/AddSpaceMemberRequestDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/CreateUserRequestDto.java
  pom.xml
Labels: Ready to Review, In Progress

#453 FAC-735: Add validation check answer rangeRangeId Used by Questions in UpdateAnswerRangeService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/CheckQuestionExistencePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerRangeMother.java
Labels: Ready to Review, P1

#463 FAC-745: Fix Duplicate Items in Questionnaire Subjects
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
Labels: Ready to Review

#451 FAC-733: Create option impacts in activating kitVersion
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitclone/CloneKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/LoadAnswerOptionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/CreateAnswerOptionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answeroption/GetQuestionOptionsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/ActivateKitVersionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/CreateQuestionImpactServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
Labels: Ready to Review, P1

#465 FAC-746:fix:Fix NPE in GetQuestionOptionsService
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
Labels: Ready to Review

#467 FAC-749 Fix NPE when loading answer ranges
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
Labels: Ready to Review

#443 FAC-695: Change kit entities code generation
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/CreateAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/CreateMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/CreateQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/CreateSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/UpdateSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/util/GenerateCodeUtil.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/UpdateSubjectServiceTest.java
Labels: Ready to Review

#468 FAC-751:feature:Prevent question update when answer range id changes
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
Labels: Ready to Review

#469 FAC-756 Change way of finding the assessment maturity level
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
Labels: In Progress

#471 FAC-757: Add null check to handle subject without attribute
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
Labels: Ready to Review

#470 FAC-728:improve:Improve findAdvisableImprovableImpactfulQuestions query
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/ImpactfulQuestionView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionIdWithAnsweredOptionIndexView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
Labels: Ready to Review

#474 FAC-723: Improve Attribute AI Insight Prompt
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/DefaultChatOptions.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
Labels: Ready to Review

#431 FAC-707:feature:Improve question update kit persister test
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/Constants.java
Labels: Ready to Review, P2

#472 FAC-743 Create customKit entity and table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/customkit/KitCustomJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.36.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review, P1

#476 FAC-763:fix:Change CreateAttributeValuePort method parameter to set
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributevalue/CreateAttributeValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.36.xml
Labels: Ready to Review, P1

#461 FAC-737: Add `Deletable` Field to GetExpertGroupMembersService
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroupaccess/GetExpertGroupMembersUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/expertgroupaccess/LoadExpertGroupMembersPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/GetExpertGroupMembersService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroupaccess/GetExpertGroupMembersUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/GetExpertGroupMembersServiceTest.java
Labels: Ready to Review, P3

#452 Fac 731 resolve get expert group service nplus one query
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupMembersCountView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupMembersView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupAccessJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupAccessJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroup/ExpertGroupMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroup/ExpertGroupPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/ExpertGroupMember.java
Labels: Ready to Review, P2

#475 FAC-759: feat - Complete CreateExpertGroupScenarioTest for Repetitive Title
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/CreateExpertGroupScenarioTest.java
Labels: Ready to Review

#478 FAC-766 Impl kit custom creation service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/customkit/KitCustomJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/customkit/KitCustomJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/seq/KitDbSequenceGenerators.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/CreateKitCustomRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/CreateKitCustomResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/CreateKitCustomRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitCustomData.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitcustom/CreateKitCustomUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitcustom/CreateKitCustomPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/CreateKitCustomService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitcustom/CreateKitCustomUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/CreateKitCustomServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/domain/KitCustomDataTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#480 FAC-769: Add kitCustomId Field to `LoadAssessmentService`
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Assessment.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/LoadAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvite/InviteAssessmentUserService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/notification/GrantAssessmentUserRoleNotificationCreator.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetComparableAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinvite/InviteAssessmentUserServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AssessmentJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaEntity.java
Labels: Ready to Review

#485 FAC-772: fix - Prevent expert group member service owner deletion
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/DeleteExpertGroupMemberService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/DeleteExpertGroupMemberServiceTest.java
Labels: Ready to Review

#481 FAC-767 Impl assessment kit custom setter service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/AssignKitCustomRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/AssignKitCustomRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/AssignKitCustomUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/UpdateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/AssignKitCustomService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/AssignKitCustomUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/AssignKitCustomServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
Labels: In Progress

#487 FAC-753:improve:Improve advice plan creation
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
Labels: Ready to Review

#486 FAC-770: Implement UpdateKitCustom Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/customkit/KitCustomJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitcustom/KitCustomJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitcustom/KitCustomJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/UpdateKitCustomRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/UpdateKitCustomRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitcustom/UpdateKitCustomUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitcustom/UpdateKitCustomPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/UpdateKitCustomService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitcustom/UpdateKitCustomUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/UpdateKitCustomServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#489 FAC-775 Impl get kit custom service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitcustom/KitCustomJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJoinAttributeView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitcustom/GetKitCustomSubjectRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitcustom/GetKitCustomSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitcustom/CreateKitCustomPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitcustom/LoadKitCustomPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/CreateKitCustomService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitcustom/GetKitCustomSubjectUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/CreateKitCustomServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#490 FAC-781: Ensure KitVersion Status uniqueness
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.37.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
Labels: Ready to Review

#497 FAC-788 Fix ordering issue in get kit custom subjects service
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
Labels: Ready to Review

#460 FAC-732 Fix update questionnaire order service n+1 query problem
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
Labels: Ready to Merge

#482 FAC-762:feature:Add code to AnswerRange
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/GenerateHashCodeUtil.java
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/pom.xml
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/config/db/PopulateAnswerRangeCodeColumnTask.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.37.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/CreateAnswerRangePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/UpdateAnswerRangePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answeroption/CreateAnswerOptionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/CreateAnswerRangeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/CreateAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/CreateMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/CreateQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/UpdateQuestionnaireService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/CreateSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/UpdateSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/CreateAnswerRangeServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/UpdateAnswerRangeServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/UpdateSubjectServiceTest.java
Labels: Ready to Merge, P1

#494 FAC-773: Remove `GetAttributeEvidenceList` Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/GetAttributeEvidenceListRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetAttributeEvidenceListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/LoadAttributeEvidencesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetAttributeEvidenceListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/GetAttributeEvidenceListUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetAttributeEvidenceListServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: Ready to Review

#495 FAC-783: fix new kit version validation
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/CountKitVersionStatsView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitversion/KitVersionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitversion/KitVersionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitversion/CountKitVersionStatsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/KitVersionValidator.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/KitVersionValidatorTest.java
Labels: Ready to Review

#496 FAC-780 Validate kit custom services
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/UpdateAssessmentPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitcustom/KitCustomPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAllAttributesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAttributesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitcustom/UpdateKitCustomPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/CreateKitCustomService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/UpdateKitCustomService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionImpactsService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/CreateKitCustomServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/UpdateKitCustomServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/GetQuestionImpactsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
Labels: Ready to Review, P1

#488 FAC:771- Implement LeaveExpertGroup Service
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupAccessJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroupaccess/LeaveExpertGroupRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/ExpertGroupAccess.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/ExpertGroupAccessStatus.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroupaccess/LeaveExpertGroupUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/ConfirmExpertGroupInvitationService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroupaccess/LeaveExpertGroupService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroupaccess/LeaveExpertGroupUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/ConfirmExpertGroupInvitationServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/LeaveExpertGroupServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/UpdateExpertGroupLastSeenServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/test/fixture/application/ExpertGroupAccessMother.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review, P2

#500 FAC-794: Create AdviceItemTable
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/AdviceItem.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/CostLevel.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/ImpactLevel.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevel.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/CostLevelTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/ImpactLevelTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/domain/adviceitem/PriorityLevelTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.37.xml
Labels: Ready to Review, P1
