Repository flickit-platform/flickit-assessment, pull requests merged in 2024-09, with the labels that each got.

#326 FAC-574 Notif kit creator when an assessment created based on the kit
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/NotificationType.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/notification/NotificationAspect.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/CreateAssessmentNovuRequestConverter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentkit/LoadKitInfoPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationPayload.java
Labels: Ready to Review

#332 FAC-573: Implement Notification to Assessment Creator After Submitting Last Answer
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/NotificationType.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/answer/SubmitAnswerRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/SubmitAnswerNovuRequestConvertor.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/notification/CreateAssessmentNotificationCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/notification/GrantAssessmentUserRoleNotificationCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/notification/SubmitAnswerNotificationCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/SubmitAnswerUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentuserrole/GrantUserAssessmentRoleUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationPayload.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GrantUserAssessmentRoleService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/notification/GrantAssessmentUserRoleNotificationCreator.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GrantUserAssessmentRoleServiceTest.java
Labels: Ready to Review

#333 FAC-617: Change EXPORT_ASSESSMENT_REPORT Permission from ASSESSOR to VIEWER Role
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
Labels: Ready to Review

#330 FAC-605: Feat - Add uniqueness constraint to database and translate it
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/constraint/AssessmentCoreDataConstraintErrorMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.29.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.31.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#340 FAC-620: Add Editable and Deletable Fields to Items in `evidenceList`
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java
Labels: Ready to Merge

#343 FAC-623 Refactor GetAttributeInsightService & its tests
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
Labels: Ready to Review

#339 FAC-585 Check All questions have been answered before Ai insight creation
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
Labels: Ready to Merge

#342 FAC-621:fix:Add SOFT_SCORE_FACTOR to PlanConstraintProvider
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advice/PlanConstraintProvider.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advice/PlanConstraintProviderMultipleTargetTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advice/PlanConstraintProviderTest.java
Labels: Ready to Review

#344 FAC-622: Use Spring AI in Attribute AI Insight Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AssessmentCommonAutoConfig.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/DefaultChatOptions.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/openai/OpenAiAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
  flickit-assessment-server/src/main/resources/application-dev.properties
  pom.xml
Labels: Ready to Review

#345 FAC-628: Implement Creation of Advice Narration Table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.31.xml
Labels: Ready to Review

#338 FAC-618 Add assessee as a field to assessment jpa entity
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/UpdateAssessmentRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/UpdateAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Assessment.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/UpdateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CreateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/UpdateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/UpdateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/UpdateAssessmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/UpdateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AssessmentJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.31.xml
Labels: Ready to Review

#350 FAC-616:fix:Fix subject default insight
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
Labels: Ready to Review

#351 FAC-631:fix:Check assessment existence in CheckAssessmentSpaceMemberhipPort
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
Labels: Ready to Review

#334 FAC-607:feature:Add AddAssessmentAnalysisInputFileUseCase
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentanalysis/AddAssessmentAnalysisInputFileRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentanalysis/AddAssessmentAnalysisInputFileRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/minio/MinioAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentanalysis/AssessmentAnalysisMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentanalysis/AssessmentAnalysisPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnalysisType.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentAnalysis.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentanalysis/AddAssessmentAnalysisInputFileUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentanalysis/CreateAssessmentAnalysisPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentanalysis/LoadAssessmentAnalysisPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentanalysis/UpdateAssessmentAnalysisInputPathPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/DeleteEvidenceAttachmentFilePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/DeleteFilePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/UploadAssessmentAnalysisInputFilePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentanalysis/AddAssessmentAnalysisInputFileService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidenceattachment/DeleteEvidenceAttachmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnalysisTypeTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentanalysis/AddAssessmentAnalysisInputFileUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentanalysis/AddAssessmentAnalysisInputFileServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidenceattachment/DeleteEvidenceAttachmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentAnalysisMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentanalysis/AssessmentAnalysisJpaRepository.java
Labels: In Progress

#347 FAC-627: Implement Create Advice Narration Service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advice/CreateAdviceRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/CreateAdviceAiNarrationRequestDto.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/CreateAdviceAiNarrationRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/advicenarration/AdviceNarrationMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/advicenarration/AdviceNarrationPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AdviceNarration.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AssessmentResult.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advice/CreateAdviceUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAdviceAiNarrationUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/advicenarration/CreateAdviceNarrationPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/advicenarration/LoadAdviceNarrationPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/advicenarration/UpdateAdviceNarrationPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessmentresult/LoadAssessmentResultPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advice/CreateAdviceService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiAiNarrationService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/MessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advice/CreateAdviceUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAdviceAiNarrationUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advice/CreateAdviceServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AdviceListItemMother.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AttributeLevelTargetMother.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/openai/OpenAiAdapter.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/port/out/CallAiPromptPort.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/openai/OpenAiAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/CreateAttributeAiInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/MessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaRepository.java
Labels: Ready to Review

#352 FAC-629 Impl get advice narration service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/GetAdviceNarrationRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AdviceNarration.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/GetAdviceNarrationUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiAiNarrationService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/MessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advicenarration/GetAdviceNarrationUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAdviceAiNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
Labels: Ready to Review

#353 FAC-633 Impl create assessor advice narration service
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/CreateAssessorAdviceNarrationRequestDto.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/in/rest/advicenarration/CreateAssessorAdviceNarrationRestController.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/advicenarration/AdviceNarrationPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAssessorAdviceNarrationUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/advicenarration/UpdateAdviceNarrationPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAssessorAdviceNarrationService.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/common/ErrorMessageKey.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/port/in/advicenarration/CreateAssessorAdviceNarrationUseCaseParamTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAssessorAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/resources/postman/flickit-advice-engine.postman_collection.json
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/advicenarration/AdviceNarrationJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.31.xml
Labels: In Progress

#354 FAC-600: Implement Assessor Insight Limitation in UpdateAttributeInsight
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/UpdateAttributeInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/UpdateAttributeInsightUseCaseParamTest.java
Labels: Ready to Review

#355 FAC-637: Fix Error Message on Empty Short Title During Assessment Creation
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java
Labels: Ready to Review

#360 FAC-641:feature:Add aiEnabled to GetAdviceNarrationUseCase.Result
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/advicenarration/GetAdviceNarrationUseCase.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/GetAdviceNarrationServiceTest.java
Labels: Ready to Review

#349 FAC-625:feature:Add user mail to NotificationEnvelope
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/AbstractNovuRequestConverter.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/SendNotificationNovuAdapter.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/notification/NotificationEnvelope.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/user/UserMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/User.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/notification/SubmitAnswerNotificationPayload.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/CreateAssessmentNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/notification/GrantAssessmentUserRoleNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/notification/GrantAssessmentUserRoleNotificationPayload.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinvite/InviteAssessmentUserServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/UserMother.java
Labels: Ready to Review

#363 FAC-638:fix:Fix confidence value in insight
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
Labels: Ready to Review

#311 FAC-569:feature:Impl GetUserSubscriberHash service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/NovuSettingProvider.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/notification/NotificationSenderSettingProvider.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/adapter/out/novu/NovuSettingProviderTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/notification/GetNotificationPlatformSettingsRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/notification/GetNotificationPlatformSettingsUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/notification/GetNotificationPlatformSettingsService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/notification/GetNotificationPlatformSettingsUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/notification/GetNotificationPlatformSettingsServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: In Progress

#369 FAC-648:fix:Remove subject-default-insight duplication
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
Labels: Ready to Review
