Repository flickit-platform/flickit-assessment, pull requests merged in 2025-03, with the labels that each got.

#659 FAC-968:impl:Impl RegenerateAllAssessmentInsights service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/RegenerateExpiredInsightsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/attribute/AttributeInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/attribute/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/subject/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/RegenerateExpiredInsightsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/attribute/UpdateAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/UpdateSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/insight/RegenerateExpiredInsightsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#662 FAC-969:impl:Impl ApproveExpiredInsights service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/ApproveExpiredInsightsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/attribute/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/subject/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/ApproveExpiredInsightsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/attribute/ApproveAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/ApproveSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/ApproveAllAssessmentInsightsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/ApproveExpiredInsightsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/insight/ApproveExpiredInsightsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/ApproveAllAssessmentInsightsServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/ApproveExpiredInsightsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/insight/attribute/AttributeInsightJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/insight/subject/SubjectInsightJpaRepository.java
Labels: Ready to Review

#650 FAC-958: Add Error Scenario Tests for Kit Creation DSL
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/kit/assessmentkit/CreateKitByDslErrorScenarioTest.java
Labels: Ready to Review

#658 FAC-966: Implement API to Check User Space Creation Limit
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateSpaceRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/AbstractScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CheckCreateSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/DeleteSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/CheckCreateSpaceRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/CheckCreateSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/CountSpacesPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CheckCreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/out/space/CheckCreateSpaceUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/CheckCreateSpaceServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#667 FAC-976: Add Missed Score and Gained Score to GetAttributeScoreDetail Service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCaseTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
Labels: Ready to Merge

#668 FAC-981: Resolve All Assessment Comments Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/ResolveAssessmentCommentsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/ResolveAssessmentCommentsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/ResolveCommentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/ResolveAssessmentCommentsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/ResolveAssessmentCommentsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/ResolveAssessmentCommentsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: Ready to Review

#664 FAC-970: Notify Admin via Email When a Premium Space is Created
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/NotificationType.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/notification/NotificationAspect.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/AspectOrders.java
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/util/AspectOrdersTest.java
  flickit-assessment-server/src/main/java/org/flickit/assessment/FlickitAssessmentApplication.java
  flickit-assessment-server/src/main/resources/application-dev.properties
  flickit-assessment-server/src/test/resources/application-test.properties
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/novu/CreatePremiumSpaceNovuRequestConverter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/notification/CreatePremiumSpaceNotificationCmd.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/CreateSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/notification/CreatePremiumSpaceNotificationCreator.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/notification/CreatePremiumSpaceNotificationPayload.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/MessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/CreateSpaceServiceTest.java
Labels: Ready to Merge

#673 FAC-984: Add Status to Space Entity
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.53.xml
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpaceMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/Space.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/SpaceStatus.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceListService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/domain/SpaceStatusTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/CreateSpaceServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceListServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/test/fixture/application/SpaceMother.java
Labels: Ready to Review

#671 FAC-983:Implement Approve All Assessment Answers Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/answer/ApproveAssessmentAnswersRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/ApproveAssessmentAnswersUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/ApproveAnswerPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/LoadAnswerPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answerhistory/CreateAnswerHistoryPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/ApproveAssessmentAnswersService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/answer/ApproveAssessmentAnswersUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/ApproveAssessmentAnswersServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
Labels: Ready to Review

#676 FAC-986: Implement Assessment Insights Issues Service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/insight/GetAssessmentInsightsIssuesRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/insight/assessment/GetAssessmentInsightsIssuesUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentInsightsIssuesService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/insight/assessment/GetAssessmentInsightsIssuesUseCaseTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentInsightsIssuesServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#645 FAC-911: Refactor - Modify `CreateSpace` Service to Support `SpaceType`
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/CreateSpaceScenarioTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/CreateSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/space/CreateSpaceUseCaseParamsTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/CreateSpaceServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#669 FAC-982: Add scenario test for create assessment
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRequestDto.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/CreateAssessmentRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/UpdateKitInfoRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/ScenarioContext.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/AssessmentTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentErrorScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/kit/assessmentkit/KitTestHelper.java
Labels: In Progress

#681 FAC-991: Add `canCreateAssessment` Field to LoadSpace Service
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceServiceTest.java
Labels: Ready to Review

#680 Fac 990 modify attribute score details service output
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/MathUtils.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeScoreDetailPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeScoreDetailServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
Labels: Ready to Review

#679 FAC-988:impl:Add GetAttributeMeasures service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAssessmentAttributeMeasuresRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasureMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasurePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Measure.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Question.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAssessmentAttributeMeasuresUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributeQuestionsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/measure/LoadMeasuresPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAssessmentAttributeMeasuresUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/MeasureMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeImpactFullQuestionsView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
Labels: Ready to Review

#683 FAC-996:impl:Clone measure entities in clone kit service
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitclone/CloneKitPersistenceJpaAdapter.java
Labels: Ready to Review

#575 FAC-866: Refactor - Modify `CreateAssessmentService` for Supporting Premium Space Feature
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/space/SpaceMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentKit.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Space.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CountAssessmentsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentkit/LoadAssessmentKitPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentkit/LoadAssessmentKitVersionIdPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/space/LoadSpacePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentKitMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SpaceMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentErrorScenarioTest.java
Labels: Ready to Review, pending
