Repository flickit-platform/flickit-assessment, pull requests merged in 2025-05, with the labels that each got.

#770 FAC-1095:fix:Fix 404 error of GetAssessmentService
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
Labels: Ready to Review

#771 FAC-1094:impl:Return translations of results in GetKitCustomSubject
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitcustom/GetKitCustomSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectServiceTest.java
Labels: Ready to Review

#777 FAC-1105: add visibility type to update assessment report publish status service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReport.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/VisibilityType.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/VisibilityTypeTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
Labels: Ready to Review

#774 FAC-1104: Implement GetPublicKits
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitListRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCaseParamTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: In Progress

#776 FAC-1106:impl:Add link_hash to AssessmentReport
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
Labels: Ready to Review

#778 FAC-1100: implement update assessment report visibility
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/UpdateAssessmentReportVisibilityRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/UpdateAssessmentReportVisibilityRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReport.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/UpdateAssessmentReportVisibilityUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/CreateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportVisibilityService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/UpdateAssessmentReportVisibilityUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportVisibilityServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionimpact/GetQuestionImpactsServiceTest.java
Labels: Ready to Review

#769 FAC-1093:impl:Create advice narration based on assessment lang
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/AssessmentResult.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessment/LoadAssessmentKitLanguagePort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/atribute/LoadAttributesPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/test/fixture/application/AssessmentResultMother.java
Labels: Ready to Review

#781 FAC-1109: Add visibility to result
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
Labels: Ready to Review

#780 FAC-1107:impl:Impl GetAssessmentPublicReport
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/jwt/UserContext.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/GetAssessmentPublicReportRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentPublicReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/LoadAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/LoadAssessmentResultPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentPublicReportUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
Labels: Ready to Review

#782 FAC-1111: Implement Public API for GetAssessmentKit
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetPublishedKitRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#783 FAC-1112: Add expertgroup to get assessment kit use case
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/ExpertGroupMother.java
Labels: Ready to Review

#785 FAC-1118: Add `canShareReport` and `canManageVisibility` to GetAssess…
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
Labels: Ready to Review

#768 FAC-1092:impl:Return fields translated in SearchKitOptions
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitSearchSpecification.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsService.java
Labels: Ready to Review

#772 FAC-1083: Implement Remove Unused Kits Script
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
Labels: Ready to Review

#787 FAC-1120:impl: Edit deploy job
  .github/workflows/ci-cd.yml
Labels: Ready to Review

#789 FAC-1121: Add `mode` to assessment
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentMode.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CreateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentModeTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AssessmentJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.59.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#790 FAC-1122: Implement UpdateAssessmentMode Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/UpdateAssessmentModeRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/UpdateAssessmentModeRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/UpdateAssessmentModeUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/UpdateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/UpdateAssessmentModeService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/UpdateAssessmentModeUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/UpdateAssessmentModeServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
Labels: Ready to Review

#792 FAC-1126: Add assessment mode to GetAssessmentService
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Assessment.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentMode.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentModeTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
Labels: Ready to Review

#794 FAC-1127: Add assessment `mode` to GetSpaceAssessments service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
Labels: Ready to Review

#795 FAC-1128: Correct messages grammar
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/crud/PaginatedResponse.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/jwt/AuthTokenFilter.java
  flickit-assessment-common/src/main/resources/i18n/advice/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/advice/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/SubmitAnswerUseCase.java
Labels: Ready to Review

#793 FAC-1123: Implement PrepareReport Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/PrepareReportRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/PrepareReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/CreateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/PrepareReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/InitAssessmentInsightsHelper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsHelper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/PrepareReportUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/PrepareReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/InitAssessmentInsightsHelperTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsHelperTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/architecture/constants/ArchUnitTestConstants.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#796 FAC-1131: Add assessment `mode` to GraphicalReportServices
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentPublicReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentPublicReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
Labels: Ready to Review

#797 FAC-1129: Use Insight Helper in GenerateAllAssessmentInsightsService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsServiceTest.java
Labels: Ready to Review

#798 FAC-1130: Use RegenerateExpiredInsightsHelper in RegenerateExpiredInsightsService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsServiceTest.java
Labels: Ready to Review

#736 FAC-1050: Implement `GetSpaceService` System Test
  .github/pull_request_template.md
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/AssessmentTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/DeleteSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/GetSpaceScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java
Labels: test, Ready to Review

#799 FAC-1133: Differ Insight Templates by Assessment Mode
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/assessment/CreateAssessmentInsightHelper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/MessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/assessment/CreateAssessmentInsightHelperTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelperTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
Labels: Ready to Review
