Repository flickit-platform/flickit-assessment, pull requests merged in 2025-01, with the labels that each got.

#544 FAC-842 Impl init subject insight service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/subjectinsight/InitSubjectInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/InitSubjectInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/subjectinsight/InitSubjectInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.42.xml
Labels: Ready to Review

#554 FAC-847 Modify get subject insight service new
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
Labels: Ready to Merge, P2

#555 FAC-854: Fix - Modify `withoutEvidence` calculating in `GetDashboardBoard` Service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: Ready to Review, P1

#547 FAC-844: Correct GetAssessmentInsight Service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/GetAssessmentInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/GetSubjectInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/GetAssessmentInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java
Labels: Ready to Merge, P3

#558 FAC-852 Impl grant access to report service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GrantAccessToReportRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GrantAccessToReportRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GrantAccessToReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/GrantAccessToReportUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/UserMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review, P1

#551 FAC-836: Add Issues to `GetAssessmentQuestionnairies` Service
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionnaireListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/questionnaire/GetAssessmentQuestionnaireListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountLowConfidenceAnswersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/CountEvidencesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/questionnaire/LoadQuestionnairesByAssessmentIdPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionnaireListItemMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidencesQuestionnaireAndCountView.java
Labels: Ready to Review, P2

#566 FAC-867: Fix `NullPointerException` in `GetKitDsl` service
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
Labels: Ready to Review

#565 FAC-852 Modify the service & fix tests due to the changes
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportServiceTest.java
Labels: Ready to Review

#564 FAC-856 Modify get subject insight service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/subjectinsight/GetSubjectInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/GetSubjectInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Merge, Ready to Review

#556 FAC-851: fix - add status checking to GetExpertGroupList
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaRepository.java
Labels: Ready to Review

#569 FAC-868 Impl get users with graphical report access service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentuserrole/GetGraphicalReportUsersRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinvite/AssessmentInvitePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentuserrole/GetGraphicalReportUsersUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinvite/LoadAssessmentInviteeListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentuserrole/LoadAssessmentUsersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetGraphicalReportUsersService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentuserrole/GetGraphicalReportUsersUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetGraphicalReportUsersServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/FullUserMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserView.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
Labels: Ready to Review

#570 FAC-873-fix `countQuestionnairesQuestionsHavingEvidence` query t
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListService.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: Ready to Review

#571 FAC-874: Fix counting unresolved comments
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: Ready to Review

#563 FAC-860 Impl grant access to report notification
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/out/novu/NotificationType.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/novu/GrantAccessToReportNovuRequestConverter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/notification/GrantAccessToReportNotificationCmd.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GrantAccessToReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/GrantAccessToReportNotificationCreator.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/notification/GrantAccessToReportNotificationPayload.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/MessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GrantAccessToReportServiceTest.java
Labels: Ready to Review

#573 FAC-877: refactor - Increase Evidence Lenght
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/AddEvidenceUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/UpdateEvidenceUseCase.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/AddEvidenceUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/UpdateEvidenceUseCaseParamTest.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.44.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-server/src/main/resources/application-dev.properties
Labels: Ready to Review

#572 FAC-837: Add Issues to GetQuestionnaireQuestionsList Service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/questionnaire/GetAssessmentQuestionnaireQuestionListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/CountEvidencesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/questionnaire/GetAssessmentQuestionnaireQuestionListUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidencesQuestionAndCountView.java
Labels: Ready to Review

#580 FAC-882: Add `Permissions` object to output of SpaceAssessmentList
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/GetSpaceAssessmentListUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
Labels: Ready to Review

#577 FAC-876: refactor - Mdify Default Sort and Attribute in AttributeScoreDetails service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCase.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeScoreDetailUseCaseTest.java
Labels: Ready to Review

#579 FAC-880: Modify CreateAttributeInsight api
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeInsightRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/CreateAttributeInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attributeinsight/UpdateAttributeInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/UpdateAttributeInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/UpdateAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#583 FAC-885: Create Assessment Report Table and Entity
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml
Labels: Ready to Review

#574 FAC-831 Refactor get dsl ports and adapters
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitDslRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitdsl/LoadKitDslModelAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answerrange/LoadAnswerRangesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAttributesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitdsl/LoadKitDslModelPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadQuestionnairesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDslService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDslServiceTest.java
Labels: Ready to Review

#581 FAC-884: Implement Question Issues Service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/question/GetQuestionIssuesRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/question/GetQuestionIssuesUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidence/CountEvidencesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/question/GetQuestionIssuesService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/question/GetQuestionIssuesUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/question/GetQuestionIssuesServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: In Progress

#585 FAC-888: Implement `GetAssessmentReportMetaData` Service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/GetAssessmentReportMetadataRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReport.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReportMetadata.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportMetadataUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/LoadAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportMetadataUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml
Labels: Ready to Review

#587 Fac 886 implement create report metadata api
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/CreateAssessmentReportMetadataRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/CreateAssessmentReportMetadataRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/CreateAssessmentReportMetadataUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/CreateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/CreateAssessmentReportMetadataUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java
Labels: Ready to Review

#592 FAC-900: Add Audit Fields to Assessment Report Table
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentReport.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.46.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.47.xml
Labels: Ready to Review

#596 FAC-901:impl:Impl publishAssessmentReport service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/UpdateAssessmentReportPublishStatusRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentreport/UpdateAssessmentReportPublishStatusRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentreport/AssessmentReportPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/UpdateAssessmentReportPublishStatusUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentreport/UpdateAssessmentReportPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentreport/UpdateAssessmentReportPublishStatusUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/CreateAssessmentReportMetadataServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/UpdateAssessmentReportPublishStatusServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentreport/AssessmentReportJpaRepository.java
Labels: Ready to Review

#597 FAC-902:Impl:Add published to GetAssessmentReportMetadataUseCase Result
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportMetadataUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportMetadataServiceTest.java
Labels: Ready to Review
