Repository flickit-platform/flickit-assessment, pull requests merged in 2025-04, with the labels that each got.

#693 FAC-1004: Create `Kit Language` Table and Entity
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlanguage/KitLanguageJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlanguage/KitLanguageJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.55.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
Labels: Ready to Review

#685 FAC-980:impl:Refactor GetAssessmentReport service result
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/ReportAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentSubjectReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/ReportAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#696 FAC-1008: Implement Update Measure Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/UpdateMeasureRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/UpdateMeasureRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/measure/UpdateMeasureUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/measure/UpdateMeasureService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/measure/UpdateMeasureUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/measure/UpdateMeasureServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#701 FAC-1015: Add `translate` Column to Kit's Entities
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeJapEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/QuestionJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/SubjectJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answerrange/AnswerRangeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.55.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answerrange/AnswerRangeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/measure/MeasureMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
Labels: Ready to Review

#697 FAC-1012:impl:Prevent measure Update in MeasureUpdateKitPersister
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/MeasureUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/MeasureUpdateKitPersisterTest.java
Labels: Ready to Review

#698 FAC-1013: Implement MeasuresChangeOrder Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/UpdateMeasureOrdersRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/UpdateMeasureOrdersRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/measure/UpdateMeasureOrdersUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/measure/UpdateMeasureOrdersService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/measure/UpdateMeasureOrdersUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/measure/UpdateMeasureOrdersServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#700 FAC-1014:impl:Add languages to GetKitList result
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlanguage/KitLanguageJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitListRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitlanguage/KitLanguagePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitlanguage/LoadKitLanguagesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#707 FAC-1026: Implement CreateMeasureService
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/CreateMeasureRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/CreateMeasureRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/measure/CreateMeasureUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/measure/CreateMeasureService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/measure/CreateMeasureUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/measure/CreateMeasureServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#699 FAC-1009: Add translations to attribute
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AttributeTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/validation/EnumValidateUtils.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/UpdateAttributeRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Attribute.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/UpdateAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/AttributeUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/UpdateAttributeServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#710 FAC1024: Add `measureId` Field to UpdateQuestionUseCase
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/constraint/AssessmentKitDataConstraintErrorMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#709 FAC-1025: Add `Measure` Existence Check in Questions to KitVersionValidator Service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitversion/KitVersionValidator.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitversion/KitVersionValidatorTest.java
Labels: Ready to Review

#704 FAC-1018:impl:Add translations to UpdateSubject service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/SubjectTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/JsonUtils.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeJapEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/SubjectJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/CreateAttributeRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/attribute/CreateAttributeRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/CreateSubjectRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/CreateSubjectRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/UpdateSubjectRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/subject/UpdateSubjectRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Attribute.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Subject.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/CreateAttributeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/CreateSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/UpdateSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/CreateSubjectPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/UpdateSubjectPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/SubjectCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/SubjectUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/CreateAttributeService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/CreateSubjectService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/UpdateSubjectService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/CreateAttributeUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/CreateSubjectUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/subject/UpdateSubjectUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/SubjectCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/CreateAttributeServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/CreateSubjectServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/UpdateSubjectServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/SubjectMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#713 FAC-1028:impl:Make isPrivate optional in GetKitList service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitListRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadPublishedKitListPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitListUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListServiceTest.java
Labels: Ready to Review

#714 FAC-1031: Create `KitBanner` table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml
Labels: Ready to Review

#719 FAC-1032: Add translations to get attributes service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/JsonUtils.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/validation/EnumValidateUtils.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/CreateAttributeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/GetAttributesUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/attribute/UpdateAttributeUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/CreateSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/UpdateSubjectUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetAttributesService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetAttributesServiceTest.java
Labels: Ready to Review

#712 FAC-1020: Add `translations` to UpdateKitService
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitInfoPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: In Progress

#720 FAC-1036: Implement GetKitSliderBanners service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.56.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitbanner/GetKitSliderBannersRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitbanner/KitBannerMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitbanner/KitBannerPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitBanner.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitbanner/GetKitSliderBannersUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitbanner/LoadKitBannersPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitbanner/GetKitSliderBannersUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitBannerMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#717 FAC-1035:impl:Add kit languages to kitEditableInfo
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitlanguage/KitLanguageJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitEditableInfoResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitEditableInfoRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitlanguage/KitLanguagePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitEditableInfoUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitlanguage/LoadKitLanguagesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoServiceTest.java
Labels: Ready to Review

#705 FAC-1021: Add 'translations' to Create and Update Question Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/CreateQuestionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/CreateQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/question/UpdateQuestionRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/CreateQuestionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/CreateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/CreateQuestionService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/question/UpdateQuestionUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/CreateQuestionServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/UpdateQuestionServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#708 FAC-1022:impl:Update translations in update and create maturityLevel services
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/MaturityLevelTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/CreateMaturityLevelRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/CreateMaturityLevelRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/UpdateMaturityLevelRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/maturitylevel/UpdateMaturityLevelRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/MaturityLevel.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/CreateMaturityLevelUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/MaturityLevelCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/CreateMaturityLevelService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/CreateMaturityLevelUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/maturitylevel/UpdateMaturityLevelUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/MaturityLevelCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/MaturityLevelUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/CreateMaturityLevelServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/maturitylevel/UpdateMaturityLevelServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/MaturityLevelMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#716 FAC-1033:impl:Add translations to measure create and update services
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/MeasureTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/measure/MeasureJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/CreateMeasureRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/CreateMeasureRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/UpdateMeasureRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/measure/UpdateMeasureRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/measure/MeasureMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/measure/MeasurePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Measure.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/measure/CreateMeasureUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/measure/UpdateMeasureUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/measure/UpdateMeasurePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/measure/CreateMeasureService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/measure/UpdateMeasureService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/measure/CreateMeasureUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/measure/UpdateMeasureUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/measure/CreateMeasureServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/measure/UpdateMeasureServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Merge

#721 FAC-1034: impl add lang to kit service
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitlanguage/AddLanguageToKitRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/kitlanguage/AddLanguageToKitRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitlanguage/KitLanguagePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitlanguage/AddLanguageToKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/kitlanguage/CreateKitLanguagePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitlanguage/AddLanguageToKitService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/kitlanguage/AddLanguageToKitUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitlanguage/AddLanguageToKitServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#723 FAC-1040: Add Translations to SubjectListService
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/subject/GetSubjectListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/impl/SubjectQuestionnaireCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/updatebydsl/impl/SubjectQuestionnaireUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/SubjectMother.java
Labels: Ready to Review

#724 FAC-1042:impl:Add translations to get kit editable info service
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitEditableInfoUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitEditableInfoServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
Labels: Ready to Review

#725 FAC-1041: Add Translations to Question List service
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/Question.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/question/GetQuestionnaireQuestionsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsServiceTest.java
Labels: Ready to Review

#731 FAC-1048:impl:Correct GetKitListService lang filter in JPQLs
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
Labels: Ready to Review

#733 FAC-1052: Add Translations to AnswerRangeList Service
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/answerrange/GetAnswerRangeListUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/answerrange/GetAnswerRangeListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AnswerOptionMother.java
Labels: Ready to Review

#703 FAC-1016: Fix sort order problem
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/adviceitem/GetAdviceItemListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answerhistory/GetAnswerHistoryListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitcustom/GetKitCustomSubjectServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kittag/GetKitTagListServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetQuestionnaireQuestionsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/GetQuestionnairesServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/GetSubjectListServiceTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/CreateExpertGroupUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/GetExpertGroupListUseCase.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroup/CreateExpertGroupUseCaseParamsTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroup/GetExpertGroupListUseCaseParamsTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/GetExpertGroupListServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/GetExpertGroupMembersServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceinvitee/GetSpaceInviteesServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/GetSpaceMembersServiceTest.java
Labels: Ready to Review

#734 FAC-1051: Add `Lang_id` to Assessmentesult Table and CreateAssessmentService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/CreateAssessmentResultPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AssessmentResultJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentresult/AssessmentResultJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.57.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#688 FAC- 999: Add space editing system test
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/UpdateSpaceRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/SpaceTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/UpdateSpaceScenarioTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/UpdateSpaceRequestDto.java
Labels: test

#690 FAC-1000: implement expert group editing system test
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/UpdateExpertGroupRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/ExpertGroupTestHelper.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/expertgroup/UpdateExpertGroupScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/users/space/UpdateSpaceScenarioTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/UpdateExpertGroupRequestDto.java
Labels: test

#684 FAC-994: Add GrantUserAccessToKit Scenario Test
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GrantUserAccessToKitRequestDto.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/fixture/request/GrantUserAccessToKitRequestDtoMother.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/kit/assessmentkit/GrantUserAccessToKitScenarioTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/kit/assessmentkit/KitTestHelper.java
Labels: test, Ready to Review

#737 FAC-1055:impl:Return fields translated in GetAssessmentQuestionnaireQuestionList service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AnswerOptionTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionTranslation.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionnaireQuestionListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
Labels: Ready to Review

#739 FAC-1056:impl:Return fields translated in GetAssessmentQuestionnaireListService
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionnaireTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/SubjectTranslation.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectWithQuestionnaireIdView.java
Labels: Ready to Review

#740 FAC-1058:impl:Return fields translated in GetAssessmentReport service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AnswerOptionTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/AttributeTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/MaturityLevelTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/MeasureTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/QuestionnaireTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/SubjectTranslation.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScorePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasureMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/MaturityLevel.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
Labels: Ready to Review

#738 FAC-1053_add-langId-to-create-assessment-service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentKit.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentKitMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#743 FAC-1061:impl:Load answer with translated fields in LoadAnswerHistoryListPort
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryPersistenceJpaAdapter.java
Labels: Ready to Review

#745 FAC-1063:impl:Return fields translated in GetAssessmentAttributeMeasures
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasureMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/measure/MeasurePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/measure/LoadMeasuresPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributeMeasuresServiceTest.java
Labels: Ready to Review

#744 FAC-1062:impl:Return fields translated in GetAttributeScoreDetail
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScoreMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionnaire/QuestionnaireMapper.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/ImpactFullQuestionsView.java
Labels: Ready to Review

#750 FAC-1069:fix:Fix NPE error in AttributeMaturityScoreMapper
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributematurityscore/AttributeMaturityScoreMapper.java
Labels: Ready to Review

#751 FAC-1068:impl:Create insight translated in RegenerateExpiredInsights
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/RegenerateExpiredInsightsServiceTest.java
Labels: Ready to Review

#747 FAC-1060: Translate GetAssessmentService fileds
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentkit/LoadAssessmentKitPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
Labels: Ready to Review

#752 FAC-1065: Translate output of InitSubjectInsight Service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/InitSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelperTest.java
Labels: Ready to Review

#753 FAC-1070: Translate Attribute Fileds in GetAssessmentAttributesService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectMapper.java
Labels: Ready to Review

#754 FAC-1071: Translate MaturityLevel Fileds in GetAssessmentMaturityLevelService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsServiceTest.java
Labels: Ready to Review

#756 FAC-1073: Add `Metada` Column to AssessmentKit Table and Entity
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
Labels: Ready to Review

#758 FAC-1086:impl:Add languages to KitListItem in SearchKitOptions service
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsServiceTest.java
Labels: Ready to Review

#757 FAC-1074: Add `metadata` to UpdateKitInfo Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/kit/messages_fa.properties
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRequestDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/UpdateKitInfoRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitMetadata.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitInfoPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#761 FAC-1076: Add Kit Metadata to GetPublishedKit use case
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetPublishedKitResponseDto.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetPublishedKitRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
Labels: Ready to Review

#764 FAC-1088: Fix NPE problem in case of deleting metadata
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java
Labels: Ready to Review

#760 FAC-1085:impl:Assign lowest level to assessment after creation
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/CreateAssessmentResultPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-server/src/test/java/org/flickit/assessment/scenario/test/core/assessment/CreateAssessmentScenarioTest.java
Labels: Ready to Review

#767 FAC-1091: Support Multiple Kit Banners Sizes
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/ImageSize.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/kit/ImageSizeTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kitbanner/KitBannerJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.58.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/kitbanner/KitBannerMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/KitBanner.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/kitbanner/GetKitSliderBannersUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitbanner/GetKitSliderBannersServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/KitBannerMother.java
Labels: Ready to Review

#763 FAC-1084:impl:Return fields translated in GetKitList
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitListService.java
Labels: Ready to Review

#766 FAC-1089:impl:Return fields translated in GetPublishedKit
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/translation/KitTranslation.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetPublishedKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadAssessmentKitPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
Labels: Ready to Review
