Repository flickit-platform/flickit-assessment, pull requests merged in 2025-02, with the labels that each got.

#591 FAC-855: Add New Endpoint to Create Subject Insight
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/subjectinsight/CreateSubjectInsightRestController.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#595 FAC 904: Add AssessmentInsight new Endpoints
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/ApproveAssessmentInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/CreateAssessmentInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/GetAssessmentInsightRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinsight/InitAssessmentInsightRestController.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#602 FAC-910:Impl:Sort advice items in GetAssessmentReportService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/adviceitem/AdviceItemPersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/advice/adviceitem/AdviceItemJpaRepository.java
Labels: Ready to Review

#600 FAC-908: Add Assessment Report Issues to Get Assessment Dashboard Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/ClassUtils.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMetadataMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
Labels: Ready to Review

#593 FAC-903: Refactor InitSubjectInsight service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Subject.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectvalue/LoadSubjectValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectValueMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectvalue/SubjectValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.48.xml
Labels: Ready to Review

#604 FAC-912:impl:Add lastModificationTime to SubjectInsight
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectInsight.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/GetSubjectInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectinsight/ApproveSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/GetAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/ApproveSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/CreateSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/subjectinsight/GetSubjectInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/ApproveSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/CreateSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/GetSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.48.xml
Labels: In Progress

#611 FAC-925: Improve prompt for creating better advice items
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
Labels: Ready to Review

#608 FAC-922:impl:Add order to GetAssessmentReportService's result
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
Labels: Ready to Review

#605 FAC-916:impl:Add lastModificationTime to AssessmentInsight
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinsight/AssessmentInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentInsight.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/subjectinsight/CreateSubjectInsightUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinsight/ApproveAssessmentInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/ApproveAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/CreateAssessmentInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinsight/GetAssessmentInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attributeinsight/CreateAttributeAiInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/subjectinsight/CreateSubjectInsightUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/ApproveAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/CreateAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/GetAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/CreateSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.48.xml
Labels: Ready to Review

#606 FAC-917:impl:Count expired insights by lastModificationTime
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
Labels: Ready to Review

#610 FAC-923:impl:Check VIEW_REPORT_PREVIEW permission in GetAssessmentReportService
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/InvalidStateException.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/api/ErrorCodes.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/InvalidStateExceptionHandler.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AdviceItemMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMetadataMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentReportMother.java
Labels: Ready to Review

#613 FAC-926:impl:Add canViewDashboard permission to GetAssessmentReport's result
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
Labels: Ready to Review

#624 FAC-935:impl:Move KitLanguage enum to common
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/KitLanguage.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/kit/KitLanguageTest.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/AssessmentKit.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateAssessmentKitUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/CreateKitByDslUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/CreateAssessmentKitPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/UpdateKitInfoPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/createbydsl/CreateKitByDslService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/UpdateKitInfoUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/CreateAssessmentKitServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/UpdateKitInfoServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/AssessmentKitMother.java
Labels: Ready to Review

#614 FAC-924: Implement `GetAssessmentAttributes` Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/GetAssessmentAttributesRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAssessmentAttributesUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributesPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributesService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/GetAssessmentAttributesUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAssessmentAttributesServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attribute/AttributeMaturityLevelSubjectView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
Labels: Ready to Review

#625 FAC-938:impl:Enrich AdviceItem fields in GetAssessmentReportUseCase.Result
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/in/adviceitem/GetAdviceItemListUseCase.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/MessageBundle.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/adviceitem/CostLevel.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/adviceitem/ImpactLevel.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/adviceitem/PriorityLevel.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/adviceitem/AdviceItemMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AdviceItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AdviceItemMother.java
Labels: In Progress

#620 FAC-931: Implement Get Assessment Maturity Level
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/maturitylevel/GetAssessmentMaturityLevelsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/maturitylevel/GetAssessmentMaturityLevelsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/maturitylevel/GetAssessmentMaturityLevelsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/maturitylevel/GetAssessmentMaturityLevelsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#626 FAC-940:impl:Add Language code to GetAssessmentReportService result
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentreport/GetAssessmentReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentreport/GetAssessmentReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
Labels: Ready to Review

#536 FAC-832: Add isPrivate field to searchKitOption useCase
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/SearchKitOptionsUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/SearchKitOptionsServiceTest.java
Labels: Ready to Review, pending

#618 FAC-930:impl:Add status to AnswerJpaEntity
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerStatus.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CreateAnswerPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerStatusTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AnswerJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.49.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#627 FAC-941:impl:Assign status to submitted answer based on CurrentUser role
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Answer.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerStatus.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/UpdateAnswerPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answerhistory/AnswerHistoryJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.49.xml
Labels: Ready to Review

#629 FAC-939: Enhance Advice Items Prompt
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
Labels: Ready to Review

#631 FAC-933: Refactor OpenAi Properties
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/domain/advice/AdviceListItem.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advicenarration/CreateAiAdviceNarrationServiceTest.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/adapter/openai/OpenAiAdapter.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/port/out/CallAiPromptPort.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AssessmentCommonAutoConfig.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/DefaultChatOptions.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-server/src/main/resources/application-dev.properties
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/InviteSpaceMemberServiceTest.java
Labels: Ready to Review

#622 FAC-615:impl:Refactor SubmitAnswerService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/SubmitAnswerUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/answer/SubmitAnswerUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
Labels: In Progress

#630 FAC-942:impl:Add ApproveAnswer service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/answer/ApproveAnswerRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/answer/ApproveAnswerRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/ApproveAnswerUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/ApproveAnswerPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/ApproveAnswerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/answer/ApproveAnswerUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/ApproveAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
Labels: Ready to Review

#632 FAC-927: Feature : Add the `KitLanguage` as the Language of the `AttributeInsight`
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppAiProperties.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/assessmentkit/AssessmentKitMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentKit.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attributeinsight/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentKitMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
Labels: Ready to Review

#635 FAC-944:impl:Impl ApproveAllAssessmentInsights service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/ApproveAllAssessmentInsightsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/ApproveAllAssessmentInsightsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/ApproveAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectinsight/ApproveSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ApproveAllAssessmentInsightsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/ApproveAllAssessmentInsightsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ApproveAllAssessmentInsightsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinsight/AssessmentInsightJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectinsight/SubjectInsightJpaRepository.java
Labels: Ready to Review

#633 FAC-936: Modify Initial Insights According `KitLanguage`
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinsight/InitAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subjectinsight/InitSubjectInsightServiceTest.java
Labels: Ready to Review

#639 FAC-951: Implement GetKitLangages service
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/in/rest/assessmentkit/GetKitLanguagesRestController.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/in/assessmentkit/GetKitLanguagesUseCase.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitLanguagesService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitLanguagesServiceTest.java
  flickit-assessment-kit/src/test/resources/postman/flickit-assessment-kit.postman_collection.json
Labels: Ready to Review

#543 FAC-840: Add Type to Space Entity
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/space/SpaceType.java
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/space/SpaceTypeTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.50.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/CreateSpaceRequestDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/CreateSpaceRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpaceMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/CreateSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/space/CreateSpaceUseCaseParamsTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/CreateSpaceServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review, pending

#640 FAC-920: Enhance Metadata Checks
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/ClassUtils.java
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/util/ClassUtilsTest.java
Labels: Ready to Review

#560 FAC-862: Add Subscription Expiration Time Field to Space Table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.50.xml
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpaceMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/Space.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceListServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/UpdateSpaceLastSeenServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/test/fixture/application/SpaceMother.java
Labels: Ready to Review, pending

#641 FAC-952: Add `SpaceType` to `GetSpaceList` Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/kit/KitLanguage.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/space/SpaceType.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/messages_fa.properties
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpaceMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/Space.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/LoadSpaceListPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceListService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceListServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/UpdateSpaceLastSeenServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/test/fixture/application/SpaceMother.java
Labels: Ready to Review

#561 FAC-864: Add Space Properties to AppSpecProperties
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
Labels: Ready to Review, pending

#562 FAC-865: Define UpgradeRequired Exception
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/UpgradeRequiredException.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/api/ErrorCodes.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/UpgradeRequiredExceptionHandler.java
Labels: Ready to Review, pending

#644 FAC-955: Implement SpaceType List Service
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceTypesRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceTypesUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceTypesService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceTypesServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#647 FAC-957:fix:Fix NPE of submitting null answer for existing answer
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
Labels: Ready to Review

#648 FAC-956: Include Type in LoadSpaceService output
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/space/GetSpaceRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/space/GetSpaceUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceServiceTest.java
Labels: Ready to Review

#642 FAC-943:impl:Add GenerateAllAssessmentInsights service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GenerateAllAssessmentInsightsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributeinsight/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectinsight/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GenerateAllAssessmentInsightsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/CreateAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectinsight/CreateSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectvalue/LoadSubjectValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GenerateAllAssessmentInsightsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/GenerateAllAssessmentInsightsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GenerateAllAssessmentInsightsServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeInsightMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#652 FAC-959: Add Unapproved Answers to Assessment Dashboard
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentDashboardUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountAnswersByQuestionIdsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountAnswersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
Labels: Ready to Review

#653 FAC-960: Add `unapprovedAnswers` to Questionnaire List
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionnaireListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/CountAnswersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswersQuestionnaireAndCountView.java
Labels: Ready to Review

#654 FAC-961: Add `isUnapproved` to QuestionnaireQuestions Issues
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/questionnaire/GetAssessmentQuestionnaireQuestionListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
Labels: Ready to Review

#656 FAC-962: Add isUnapproved to Question Issues
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/question/GetQuestionIssuesUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/question/GetQuestionIssuesService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/question/GetQuestionIssuesServiceTest.java
Labels: Ready to Review

#655 FAC-965:impl:Impl CreateSubjectInsightsHelper
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/core/messages_fa.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/assessment/AssessmentInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/assessment/AssessmentInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/attribute/AttributeInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/attribute/AttributeInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/subject/SubjectInsightMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/insight/subject/SubjectInsightPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/insight/AssessmentInsight.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/insight/AttributeInsight.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/insight/SubjectInsight.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/assessment/CreateAssessmentInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/assessment/LoadAssessmentInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/assessment/UpdateAssessmentInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/attribute/CreateAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/attribute/LoadAttributeInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/attribute/LoadAttributeInsightsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/CreateSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/LoadSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/LoadSubjectInsightsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/insight/subject/UpdateSubjectInsightPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/subjectvalue/LoadSubjectValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/assessment/CreateAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/assessment/GetAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/assessment/InitAssessmentInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightHelper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/GetSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/InitSubjectInsightService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentDashboardServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/GenerateAllAssessmentInsightsServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/assessment/CreateAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/assessment/InitAssessmentInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeAiInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/attribute/CreateAttributeInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelperTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/InitSubjectInsightServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/architecture/constants/ArchUnitTestConstants.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInsightMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeInsightMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectInsightMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectvalue/SubjectValueJpaRepository.java
Labels: Ready to Review

#661 FAC-974: Fix InitSubjectInsight BadRequest Problem
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelper.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/insight/subject/CreateSubjectInsightsHelperTest.java
Labels: Ready to Review
